"""
This type stub file was generated by pyright.
"""

from typing import Literal
from . import common, doccer
from ._common import *

__all__ = ["ascent", "central_diff_weights", "derivative", "electrocardiogram", "face"]
dataset_methods: list[Literal["ascent", "face", "electrocardiogram"]]
