"""
This type stub file was generated by pyright.
"""

import numpy as np
import optype.numpy as onpt
from collections.abc import Callable
from typing import Concatenate, Literal
from typing_extensions import deprecated

__all__ = ["ascent", "central_diff_weights", "derivative", "electrocardiogram", "face"]
@deprecated("will be completely removed in SciPy 1.12.0")
def central_diff_weights(Np: int, ndiv: int = ...) -> onpt.Array[tuple[int], np.float64]:
    ...

@deprecated("will be completely removed in SciPy 1.12.0")
def derivative(func: Callable[Concatenate[float, ...], float], x0: float, dx: float = ..., n: int = ..., args: tuple[object, ...] = ..., order: int = ...) -> float:
    ...

@deprecated("will be completely removed in SciPy 1.12.0")
def ascent() -> onpt.Array[tuple[Literal[512], Literal[512]], np.uint8]:
    ...

@deprecated("will be completely removed in SciPy 1.12.0")
def face(gray: bool = ...) -> onpt.Array[tuple[Literal[768], Literal[1024]] | tuple[Literal[768], Literal[1024], Literal[3]], np.uint8]:
    ...

@deprecated("will be completely removed in SciPy 1.12.0")
def electrocardiogram() -> onpt.Array[tuple[Literal[108000]], np.float64]:
    ...

