"""
This type stub file was generated by pyright.
"""

__all__ = ["docformat", "extend_notes_in_docstring", "filldoc", "indentcount_lines", "inherit_docstring_from", "replace_notes_in_docstring", "unindent_dict", "unindent_string"]
