"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def fft(x, n: Untyped | None = ..., axis: int = ..., overwrite_x: bool = ...) -> Untyped:
    ...

def ifft(x, n: Untyped | None = ..., axis: int = ..., overwrite_x: bool = ...) -> Untyped:
    ...

def rfft(x, n: Untyped | None = ..., axis: int = ..., overwrite_x: bool = ...) -> Untyped:
    ...

def irfft(x, n: Untyped | None = ..., axis: int = ..., overwrite_x: bool = ...) -> Untyped:
    ...

def fftn(x, shape: Untyped | None = ..., axes: Untyped | None = ..., overwrite_x: bool = ...) -> Untyped:
    ...

def ifftn(x, shape: Untyped | None = ..., axes: Untyped | None = ..., overwrite_x: bool = ...) -> Untyped:
    ...

def fft2(x, shape: Untyped | None = ..., axes=..., overwrite_x: bool = ...) -> Untyped:
    ...

def ifft2(x, shape: Untyped | None = ..., axes=..., overwrite_x: bool = ...) -> Untyped:
    ...

