"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["fftfreq", "fftshift", "ifftshift", "next_fast_len", "rfftfreq"]
def rfftfreq(n, d: float = ...) -> Untyped:
    ...

def next_fast_len(target) -> Untyped:
    ...

