"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

odr: Untyped
class OdrWarning(UserWarning):
    ...


class OdrError(Exception):
    ...


class OdrStop(Exception):
    ...


odr_error = OdrError
odr_stop = OdrStop
class Data:
    x: Untyped
    y: Untyped
    we: Untyped
    wd: Untyped
    fix: Untyped
    meta: Untyped
    def __init__(self, x, y: Untyped | None = ..., we: Untyped | None = ..., wd: Untyped | None = ..., fix: Untyped | None = ..., meta: Untyped | None = ...) -> None:
        ...
    
    def set_meta(self, **kwds):
        ...
    
    def __getattr__(self, attr) -> Untyped:
        ...
    


class RealData(Data):
    x: Untyped
    y: Untyped
    sx: Untyped
    sy: Untyped
    covx: Untyped
    covy: Untyped
    fix: Untyped
    meta: Untyped
    def __init__(self, x, y: Untyped | None = ..., sx: Untyped | None = ..., sy: Untyped | None = ..., covx: Untyped | None = ..., covy: Untyped | None = ..., fix: Untyped | None = ..., meta: Untyped | None = ...) -> None:
        ...
    
    def __getattr__(self, attr) -> Untyped:
        ...
    


class Model:
    fcn: Untyped
    fjacb: Untyped
    fjacd: Untyped
    extra_args: Untyped
    estimate: Untyped
    implicit: Untyped
    meta: Untyped
    def __init__(self, fcn, fjacb: Untyped | None = ..., fjacd: Untyped | None = ..., extra_args: Untyped | None = ..., estimate: Untyped | None = ..., implicit: int = ..., meta: Untyped | None = ...) -> None:
        ...
    
    def set_meta(self, **kwds):
        ...
    
    def __getattr__(self, attr) -> Untyped:
        ...
    


class Output:
    beta: Untyped
    sd_beta: Untyped
    cov_beta: Untyped
    stopreason: Untyped
    def __init__(self, output) -> None:
        ...
    
    def pprint(self):
        ...
    


class ODR:
    data: Untyped
    model: Untyped
    beta0: Untyped
    delta0: Untyped
    ifixx: Untyped
    ifixb: Untyped
    job: Untyped
    iprint: Untyped
    errfile: Untyped
    rptfile: Untyped
    ndigit: Untyped
    taufac: Untyped
    sstol: Untyped
    partol: Untyped
    maxit: Untyped
    stpb: Untyped
    stpd: Untyped
    sclb: Untyped
    scld: Untyped
    work: Untyped
    iwork: Untyped
    output: Untyped
    def __init__(self, data, model, beta0: Untyped | None = ..., delta0: Untyped | None = ..., ifixb: Untyped | None = ..., ifixx: Untyped | None = ..., job: Untyped | None = ..., iprint: Untyped | None = ..., errfile: Untyped | None = ..., rptfile: Untyped | None = ..., ndigit: Untyped | None = ..., taufac: Untyped | None = ..., sstol: Untyped | None = ..., partol: Untyped | None = ..., maxit: Untyped | None = ..., stpb: Untyped | None = ..., stpd: Untyped | None = ..., sclb: Untyped | None = ..., scld: Untyped | None = ..., work: Untyped | None = ..., iwork: Untyped | None = ..., overwrite: bool = ...) -> None:
        ...
    
    def set_job(self, fit_type: Untyped | None = ..., deriv: Untyped | None = ..., var_calc: Untyped | None = ..., del_init: Untyped | None = ..., restart: Untyped | None = ...):
        ...
    
    def set_iprint(self, init: Untyped | None = ..., so_init: Untyped | None = ..., iter: Untyped | None = ..., so_iter: Untyped | None = ..., iter_step: Untyped | None = ..., final: Untyped | None = ..., so_final: Untyped | None = ...):
        ...
    
    def run(self) -> Untyped:
        ...
    
    def restart(self, iter: Untyped | None = ...) -> Untyped:
        ...
    


