"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

class AAA:
    def __init__(self, points, values, *, rtol: Untyped | None = ..., max_terms: int = ...) -> None:
        ...
    
    def __call__(self, z) -> Untyped:
        ...
    
    def poles(self) -> Untyped:
        ...
    
    def residues(self) -> Untyped:
        ...
    
    def roots(self) -> Untyped:
        ...
    


