"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

class BSpline:
    k: Untyped
    c: Untyped
    t: Untyped
    extrapolate: Untyped
    axis: Untyped
    def __init__(self, t, c, k, extrapolate: bool = ..., axis: int = ...) -> None:
        ...
    
    @classmethod
    def construct_fast(cls, t, c, k, extrapolate: bool = ..., axis: int = ...) -> Untyped:
        ...
    
    @property
    def tck(self) -> Untyped:
        ...
    
    @classmethod
    def basis_element(cls, t, extrapolate: bool = ...) -> Untyped:
        ...
    
    @classmethod
    def design_matrix(cls, x, t, k, extrapolate: bool = ...) -> Untyped:
        ...
    
    def __call__(self, x, nu: int = ..., extrapolate: Untyped | None = ...) -> Untyped:
        ...
    
    def derivative(self, nu: int = ...) -> Untyped:
        ...
    
    def antiderivative(self, nu: int = ...) -> Untyped:
        ...
    
    def integrate(self, a, b, extrapolate: Untyped | None = ...) -> Untyped:
        ...
    
    @classmethod
    def from_power_basis(cls, pp, bc_type: str = ...) -> Untyped:
        ...
    
    def insert_knot(self, x, m: int = ...) -> Untyped:
        ...
    


def make_interp_spline(x, y, k: int = ..., t: Untyped | None = ..., bc_type: Untyped | None = ..., axis: int = ..., check_finite: bool = ...) -> Untyped:
    ...

def make_lsq_spline(x, y, t, k: int = ..., w: Untyped | None = ..., axis: int = ..., check_finite: bool = ...) -> Untyped:
    ...

def make_smoothing_spline(x, y, w: Untyped | None = ..., lam: Untyped | None = ...) -> Untyped:
    ...

def fpcheck(x, t, k):
    ...

