"""
This type stub file was generated by pyright.
"""

from typing import Literal
from scipy._typing import Untyped
from . import PPoly as PPoly

def prepare_input(x, y, axis, dydx: Untyped | None = ...) -> Untyped:
    ...

class CubicHermiteSpline(PPoly):
    axis: Untyped
    def __init__(self, x, y, dydx, axis: int = ..., extrapolate: Untyped | None = ...) -> None:
        ...
    


class PchipInterpolator(CubicHermiteSpline):
    axis: Untyped
    def __init__(self, x, y, axis: int = ..., extrapolate: Untyped | None = ...) -> None:
        ...
    


def pchip_interpolate(xi, yi, x, der: int = ..., axis: int = ...) -> Untyped:
    ...

class Akima1DInterpolator(CubicHermiteSpline):
    axis: Untyped
    def __init__(self, x, y, axis: int = ..., *, method: Literal["akima", "makima"] = ..., extrapolate: bool | None = ...) -> None:
        ...
    
    def extend(self, c, x, right: bool = ...):
        ...
    
    @classmethod
    def from_spline(cls, tck, extrapolate: Untyped | None = ...):
        ...
    
    @classmethod
    def from_bernstein_basis(cls, bp, extrapolate: Untyped | None = ...):
        ...
    


class CubicSpline(CubicHermiteSpline):
    axis: Untyped
    def __init__(self, x, y, axis: int = ..., bc_type: str = ..., extrapolate: Untyped | None = ...) -> None:
        ...
    


