"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def splprep(x, w: Untyped | None = ..., u: Untyped | None = ..., ub: Untyped | None = ..., ue: Untyped | None = ..., k: int = ..., task: int = ..., s: Untyped | None = ..., t: Untyped | None = ..., full_output: int = ..., nest: Untyped | None = ..., per: int = ..., quiet: int = ...) -> Untyped:
    ...

def splrep(x, y, w: Untyped | None = ..., xb: Untyped | None = ..., xe: Untyped | None = ..., k: int = ..., task: int = ..., s: Untyped | None = ..., t: Untyped | None = ..., full_output: int = ..., per: int = ..., quiet: int = ...) -> Untyped:
    ...

def splev(x, tck, der: int = ..., ext: int = ...) -> Untyped:
    ...

def splint(a, b, tck, full_output: int = ...) -> Untyped:
    ...

def sproot(tck, mest: int = ...) -> Untyped:
    ...

def spalde(x, tck) -> Untyped:
    ...

def insert(x, tck, m: int = ..., per: int = ...) -> Untyped:
    ...

def splder(tck, n: int = ...) -> Untyped:
    ...

def splantider(tck, n: int = ...) -> Untyped:
    ...

