"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["RBFInterpolator"]
class RBFInterpolator:
    y: Untyped
    d: Untyped
    d_shape: Untyped
    d_dtype: Untyped
    neighbors: Untyped
    smoothing: Untyped
    kernel: Untyped
    epsilon: Untyped
    powers: Untyped
    def __init__(self, y: Untyped, d: Untyped, neighbors: Untyped | None = ..., smoothing: float = ..., kernel: str = ..., epsilon: Untyped | None = ..., degree: Untyped | None = ...) -> None:
        ...
    
    def __call__(self, x: Untyped) -> Untyped:
        ...
    


