"""
This type stub file was generated by pyright.
"""

import numpy as np
import numpy.typing as npt
import optype.numpy as onpt
from typing import Any
from typing_extensions import override

class NDInterpolatorBase:
    def __init__(self, /, points: onpt.AnyIntegerArray | onpt.AnyFloatingArray, values: onpt.AnyFloatingArray, fill_value: float = ..., ndim: int | None = ..., rescale: bool = ..., need_contiguous: bool = ..., need_values: bool = ...) -> None:
        ...
    
    def __call__(self, /, *args: onpt.AnyFloatingArray) -> npt.NDArray[np.floating[Any]]:
        ...
    


class LinearNDInterpolator(NDInterpolatorBase):
    @override
    def __init__(self, /, points: onpt.AnyIntegerArray | onpt.AnyFloatingArray, values: onpt.AnyFloatingArray, fill_value: float = ..., rescale: bool = ...) -> None:
        ...
    


class CloughTocher2DInterpolator(NDInterpolatorBase):
    @override
    def __init__(self, /, points: onpt.AnyIntegerArray | onpt.AnyFloatingArray, values: onpt.AnyFloatingArray, fill_value: float = ..., tol: float = ..., maxiter: int = ..., rescale: bool = ...) -> None:
        ...
    


