"""
This type stub file was generated by pyright.
"""

import numpy as np
import numpy.typing as npt
from numpy._typing import _ArrayLikeComplex_co, _ArrayLikeInt_co

def lambertw(z: _ArrayLikeComplex_co, k: _ArrayLikeInt_co = ..., tol: float | np.float64 = ...) -> np.complex128 | npt.NDArray[np.complex128]:
    ...

