"""
This type stub file was generated by pyright.
"""

import numpy as np
import numpy.typing as npt
import scipy._typing as spt
from numpy._typing import _ArrayLikeFloat_co

__all__ = ["multigammaln"]
def multigammaln(a: _ArrayLikeFloat_co, d: spt.AnyInt) -> np.float64 | npt.NDArray[np.float64]:
    ...

