"""
This type stub file was generated by pyright.
"""

__all__ = ["chdtrc", "entr", "erf", "erfc", "expit", "gammainc", "gammaincc", "gammaln", "i0", "i0e", "i1", "i1e", "log_ndtr", "logit", "ndtr", "ndtri", "rel_entr", "xlogy"]
