"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

sys_is_le: Untyped
native_code: Untyped
swapped_code: Untyped
aliases: Untyped
def to_numpy_code(code) -> Untyped:
    ...

