"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped
from ._miobase import MatFileReader as MatFileReader

class MatFile5Reader(MatFileReader):
    uint16_codec: Untyped
    def __init__(self, mat_stream, byte_order: Untyped | None = ..., mat_dtype: bool = ..., squeeze_me: bool = ..., chars_as_strings: bool = ..., matlab_compatible: bool = ..., struct_as_record: bool = ..., verify_compressed_data_integrity: bool = ..., uint16_codec: Untyped | None = ..., simplify_cells: bool = ...) -> None:
        ...
    
    def guess_byte_order(self) -> Untyped:
        ...
    
    def read_file_header(self) -> Untyped:
        ...
    
    def initialize_read(self):
        ...
    
    def read_var_header(self) -> Untyped:
        ...
    
    def read_var_array(self, header, process: bool = ...) -> Untyped:
        ...
    
    def get_variables(self, variable_names: Untyped | None = ...) -> Untyped:
        ...
    
    def list_variables(self) -> Untyped:
        ...
    


def varmats_from_mat(file_obj) -> Untyped:
    ...

class EmptyStructMarker:
    ...


def to_writeable(source) -> Untyped:
    ...

NDT_FILE_HDR: Untyped
NDT_TAG_FULL: Untyped
NDT_TAG_SMALL: Untyped
NDT_ARRAY_FLAGS: Untyped
class VarWriter5:
    mat_tag: Untyped
    file_stream: Untyped
    unicode_strings: Untyped
    long_field_names: Untyped
    oned_as: Untyped
    def __init__(self, file_writer) -> None:
        ...
    
    def write_bytes(self, arr):
        ...
    
    def write_string(self, s):
        ...
    
    def write_element(self, arr, mdtype: Untyped | None = ...):
        ...
    
    def write_smalldata_element(self, arr, mdtype, byte_count):
        ...
    
    def write_regular_element(self, arr, mdtype, byte_count):
        ...
    
    def write_header(self, shape, mclass, is_complex: bool = ..., is_logical: bool = ..., nzmax: int = ...):
        ...
    
    def update_matrix_tag(self, start_pos):
        ...
    
    def write_top(self, arr, name, is_global):
        ...
    
    def write(self, arr):
        ...
    
    def write_numeric(self, arr):
        ...
    
    def write_char(self, arr, codec: str = ...):
        ...
    
    def write_sparse(self, arr):
        ...
    
    def write_cells(self, arr):
        ...
    
    def write_empty_struct(self):
        ...
    
    def write_struct(self, arr):
        ...
    
    def write_object(self, arr):
        ...
    


class MatFile5Writer:
    file_stream: Untyped
    do_compression: Untyped
    unicode_strings: Untyped
    global_vars: Untyped
    long_field_names: Untyped
    oned_as: Untyped
    def __init__(self, file_stream, do_compression: bool = ..., unicode_strings: bool = ..., global_vars: Untyped | None = ..., long_field_names: bool = ..., oned_as: str = ...) -> None:
        ...
    
    def write_file_header(self):
        ...
    
    def put_variables(self, mdict, write_header: Untyped | None = ...):
        ...
    


