"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Final, Literal, TypedDict, overload

__all__ = ["show"]
_ConfigDict = TypedDict("_ConfigDict", { "Compilers": dict[str, dict[str, str]],"Machine Information": dict[str, dict[str, str] | bool],"Build Dependencies": dict[str, dict[str, str | bool]],"Python Information": dict[str, str] })
_built_with_meson: Final[bool]
class DisplayModes(Enum):
    stdout = ...
    dicts = ...


CONFIG: Final[_ConfigDict]
@overload
def show(mode: Literal["stdout"] = ...) -> _ConfigDict:
    ...

@overload
def show(mode: Literal["dicts"]) -> _ConfigDict:
    ...

