"""
This type stub file was generated by pyright.
"""

from collections.abc import Generator

__all__ = ["get_workers", "good_size", "prev_good_size", "set_workers"]
def set_workers(workers: int) -> Generator[None, None, None]:
    ...

def get_workers() -> int:
    ...

