"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def axis_slice(a, start: Untyped | None = ..., stop: Untyped | None = ..., step: Untyped | None = ..., axis: int = ...) -> Untyped:
    ...

def axis_reverse(a, axis: int = ...) -> Untyped:
    ...

def odd_ext(x, n, axis: int = ...) -> Untyped:
    ...

def even_ext(x, n, axis: int = ...) -> Untyped:
    ...

def const_ext(x, n, axis: int = ...) -> Untyped:
    ...

def zero_ext(x, n, axis: int = ...) -> Untyped:
    ...

