"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def czt_points(m, w: Untyped | None = ..., a: complex = ...) -> Untyped:
    ...

class CZT:
    def __init__(self, n, m: Untyped | None = ..., w: Untyped | None = ..., a: complex = ...) -> None:
        ...
    
    def __call__(self, x, *, axis: int = ...) -> Untyped:
        ...
    
    def points(self) -> Untyped:
        ...
    


class ZoomFFT(CZT):
    w: Untyped
    a: Untyped
    def __init__(self, n, fn, m: Untyped | None = ..., *, fs: int = ..., endpoint: bool = ...) -> None:
        ...
    


def czt(x, m: Untyped | None = ..., w: Untyped | None = ..., a: complex = ..., *, axis: int = ...) -> Untyped:
    ...

def zoom_fft(x, fn, m: Untyped | None = ..., *, fs: int = ..., endpoint: bool = ..., axis: int = ...) -> Untyped:
    ...

