"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def tf2ss(num, den) -> Untyped:
    ...

def abcd_normalize(A: Untyped | None = ..., B: Untyped | None = ..., C: Untyped | None = ..., D: Untyped | None = ...) -> Untyped:
    ...

def ss2tf(A, B, C, D, input: int = ...) -> Untyped:
    ...

def zpk2ss(z, p, k) -> Untyped:
    ...

def ss2zpk(A, B, C, D, input: int = ...) -> Untyped:
    ...

def cont2discrete(system, dt, method: str = ..., alpha: Untyped | None = ...) -> Untyped:
    ...

