"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def max_len_seq(nbits, state: Untyped | None = ..., length: Untyped | None = ..., taps: Untyped | None = ...) -> Untyped:
    ...

