"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["argrelextrema", "argrelmax", "argrelmin", "find_peaks", "find_peaks_cwt", "peak_prominences", "peak_widths"]
def argrelmin(data: Untyped, axis: int = ..., order: int = ..., mode: str = ...) -> Untyped:
    ...

def argrelmax(data: Untyped, axis: int = ..., order: int = ..., mode: str = ...) -> Untyped:
    ...

def argrelextrema(data: Untyped, comparator: Untyped, axis: int = ..., order: int = ..., mode: str = ...) -> Untyped:
    ...

def peak_prominences(x: Untyped, peaks: Untyped, wlen: Untyped | None = ...) -> Untyped:
    ...

def peak_widths(x: Untyped, peaks: Untyped, rel_height: float = ..., prominence_data: Untyped | None = ..., wlen: Untyped | None = ...) -> Untyped:
    ...

def find_peaks(x: Untyped, height: Untyped | None = ..., threshold: Untyped | None = ..., distance: Untyped | None = ..., prominence: Untyped | None = ..., width: Untyped | None = ..., wlen: Untyped | None = ..., rel_height: float = ..., plateau_size: Untyped | None = ...) -> Untyped:
    ...

def find_peaks_cwt(vector: Untyped, widths: Untyped, wavelet: Untyped | None = ..., max_distances: Untyped | None = ..., gap_thresh: Untyped | None = ..., min_length: Untyped | None = ..., min_snr: int = ..., noise_perc: int = ..., window_size: Untyped | None = ...) -> Untyped:
    ...

