"""
This type stub file was generated by pyright.
"""

from numpy.typing import NDArray
import numpy as np
from scipy._typing import Untyped

def savgol_coeffs(window_length, polyorder, deriv: int = ..., delta: float = ..., pos: Untyped | None = ..., use: str = ...) -> Untyped:
    ...

def savgol_filter(
    x: NDArray[np.float64]|list[float|int],
    window_length: int,
    polyorder: int,
    deriv: int = ...,
    delta: float = ...,
    axis: int = ...,
    mode: str = ...,
    cval: float = ...
) -> NDArray[np.float64]:
    ...

