"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def lombscargle(x, y, freqs, precenter: bool = ..., normalize: bool = ...) -> Untyped:
    ...

def periodogram(x, fs: float = ..., window: str = ..., nfft: Untyped | None = ..., detrend: str = ..., return_onesided: bool = ..., scaling: str = ..., axis: int = ...) -> Untyped:
    ...

def welch(x, fs: float = ..., window: str = ..., nperseg: Untyped | None = ..., noverlap: Untyped | None = ..., nfft: Untyped | None = ..., detrend: str = ..., return_onesided: bool = ..., scaling: str = ..., axis: int = ..., average: str = ...) -> Untyped:
    ...

def csd(x, y, fs: float = ..., window: str = ..., nperseg: Untyped | None = ..., noverlap: Untyped | None = ..., nfft: Untyped | None = ..., detrend: str = ..., return_onesided: bool = ..., scaling: str = ..., axis: int = ..., average: str = ...) -> Untyped:
    ...

def spectrogram(x, fs: float = ..., window=..., nperseg: Untyped | None = ..., noverlap: Untyped | None = ..., nfft: Untyped | None = ..., detrend: str = ..., return_onesided: bool = ..., scaling: str = ..., axis: int = ..., mode: str = ...) -> Untyped:
    ...

def check_COLA(window, nperseg, noverlap, tol: float = ...) -> Untyped:
    ...

def check_NOLA(window, nperseg, noverlap, tol: float = ...) -> Untyped:
    ...

def stft(x, fs: float = ..., window: str = ..., nperseg: int = ..., noverlap: Untyped | None = ..., nfft: Untyped | None = ..., detrend: bool = ..., return_onesided: bool = ..., boundary: str = ..., padded: bool = ..., axis: int = ..., scaling: str = ...) -> Untyped:
    ...

def istft(Zxx, fs: float = ..., window: str = ..., nperseg: Untyped | None = ..., noverlap: Untyped | None = ..., nfft: Untyped | None = ..., input_onesided: bool = ..., boundary: bool = ..., time_axis: int = ..., freq_axis: int = ..., scaling: str = ...) -> Untyped:
    ...

def coherence(x, y, fs: float = ..., window: str = ..., nperseg: Untyped | None = ..., noverlap: Untyped | None = ..., nfft: Untyped | None = ..., detrend: str = ..., axis: int = ...) -> Untyped:
    ...

