"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def spline_filter(Iin, lmbda: float = ...) -> Untyped:
    ...

def gauss_spline(x, n) -> Untyped:
    ...

def compute_root_from_lambda(lamb) -> Untyped:
    ...

def cspline1d(signal, lamb: float = ...) -> Untyped:
    ...

def qspline1d(signal, lamb: float = ...) -> Untyped:
    ...

def collapse_2d(x, axis) -> Untyped:
    ...

def symiirorder_nd(func, input, *args, axis: int = ..., **kwargs) -> Untyped:
    ...

def qspline2d(signal, lamb: float = ..., precision: float = ...) -> Untyped:
    ...

def cspline2d(signal, lamb: float = ..., precision: float = ...) -> Untyped:
    ...

def cspline1d_eval(cj, newx, dx: float = ..., x0: int = ...) -> Untyped:
    ...

def qspline1d_eval(cj, newx, dx: float = ..., x0: int = ...) -> Untyped:
    ...

def symiirorder1(signal, c0, z1, precision: float = ...) -> Untyped:
    ...

def symiirorder2(input, r, omega, precision: float = ...) -> Untyped:
    ...

