"""
This type stub file was generated by pyright.
"""

import numpy as np
import numpy.typing as npt
import optype.numpy as onpt
from typing import Any, Literal, TypeAlias

__all__ = ["_output_len", "upfirdn"]
_FIRMode: TypeAlias = Literal["constant", "symmetric", "reflect", "wrap"]
_int64_t: TypeAlias = int | np.int64
class _UpFIRDn:
    def __init__(self, /, h: npt.NDArray[np.floating[Any]], x_dtype: np.dtype[np.floating[Any]], up: int, down: int) -> None:
        ...
    
    def apply_filter(self, x: npt.NDArray[np.number[Any]], axis: int = ..., mode: _FIRMode = ..., cval: int = ...) -> npt.NDArray[np.floating[Any]]:
        ...
    


def upfirdn(h: onpt.AnyFloatingArray, x: onpt.AnyIntegerArray | onpt.AnyFloatingArray, up: int = ..., down: int = ..., axis: int = ..., mode: _FIRMode = ..., cval: float = ...) -> npt.NDArray[np.floating[Any]]:
    ...

