"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def sawtooth(t, width: int = ...) -> Untyped:
    ...

def square(t, duty: float = ...) -> Untyped:
    ...

def gausspulse(t, fc: int = ..., bw: float = ..., bwr: int = ..., tpr: int = ..., retquad: bool = ..., retenv: bool = ...) -> Untyped:
    ...

def chirp(t, f0, t1, f1, method: str = ..., phi: int = ..., vertex_zero: bool = ...) -> Untyped:
    ...

def sweep_poly(t, poly, phi: int = ...) -> Untyped:
    ...

def unit_impulse(shape, idx: Untyped | None = ..., dtype=...) -> Untyped:
    ...

