"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def gcrotmk(A, b, x0: Untyped | None = ..., *, rtol: float = ..., atol: float = ..., maxiter: int = ..., M: Untyped | None = ..., callback: Untyped | None = ..., m: int = ..., k: Untyped | None = ..., CU: Untyped | None = ..., discard_C: bool = ..., truncate: str = ...) -> Untyped:
    ...

