"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def bicg(A, b, x0: Untyped | None = ..., *, rtol: float = ..., atol: float = ..., maxiter: Untyped | None = ..., M: Untyped | None = ..., callback: Untyped | None = ...) -> Untyped:
    ...

def bicgstab(A, b, x0: Untyped | None = ..., *, rtol: float = ..., atol: float = ..., maxiter: Untyped | None = ..., M: Untyped | None = ..., callback: Untyped | None = ...) -> Untyped:
    ...

def cg(A, b, x0: Untyped | None = ..., *, rtol: float = ..., atol: float = ..., maxiter: Untyped | None = ..., M: Untyped | None = ..., callback: Untyped | None = ...) -> Untyped:
    ...

def cgs(A, b, x0: Untyped | None = ..., *, rtol: float = ..., atol: float = ..., maxiter: Untyped | None = ..., M: Untyped | None = ..., callback: Untyped | None = ...) -> Untyped:
    ...

def gmres(A, b, x0: Untyped | None = ..., *, rtol: float = ..., atol: float = ..., restart: Untyped | None = ..., maxiter: Untyped | None = ..., M: Untyped | None = ..., callback: Untyped | None = ..., callback_type: Untyped | None = ...) -> Untyped:
    ...

def qmr(A, b, x0: Untyped | None = ..., *, rtol: float = ..., atol: float = ..., maxiter: Untyped | None = ..., M1: Untyped | None = ..., M2: Untyped | None = ..., callback: Untyped | None = ...) -> Untyped:
    ...

