"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def lgmres(A, b, x0: Untyped | None = ..., *, rtol: float = ..., atol: float = ..., maxiter: int = ..., M: Untyped | None = ..., callback: Untyped | None = ..., inner_m: int = ..., outer_k: int = ..., outer_v: Untyped | None = ..., store_outer_Av: bool = ..., prepend_outer_v: bool = ...) -> Untyped:
    ...

