"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def lsmr(A, b, damp: float = ..., atol: float = ..., btol: float = ..., conlim: float = ..., maxiter: Untyped | None = ..., show: bool = ..., x0: Untyped | None = ...) -> Untyped:
    ...

