"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

eps: Untyped
def lsqr(A, b, damp: float = ..., atol: float = ..., btol: float = ..., conlim: float = ..., iter_lim: Untyped | None = ..., show: bool = ..., calc_var: bool = ..., x0: Untyped | None = ...) -> Untyped:
    ...

