"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def minres(A, b, x0: Untyped | None = ..., *, rtol: float = ..., shift: float = ..., maxiter: Untyped | None = ..., M: Untyped | None = ..., callback: Untyped | None = ..., show: bool = ..., check: bool = ...) -> Untyped:
    ...

