"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def tfqmr(A, b, x0: Untyped | None = ..., *, rtol: float = ..., atol: float = ..., maxiter: Untyped | None = ..., M: Untyped | None = ..., callback: Untyped | None = ..., show: bool = ...) -> Untyped:
    ...

