"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__docformat__: str
def coerce(x, y) -> Untyped:
    ...

def id(x) -> Untyped:
    ...

def make_system(A, M, x0, b) -> Untyped:
    ...

