"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["block_array", "block_diag", "bmat", "diags", "diags_array", "eye", "eye_array", "hstack", "identity", "kron", "kronsum", "rand", "random", "random_array", "spdiags", "vstack"]
def spdiags(data: Untyped, diags: Untyped, m: Untyped | None = ..., n: Untyped | None = ..., format: Untyped | None = ...) -> Untyped:
    ...

def diags_array(diagonals: Untyped, /, *, offsets: int = ..., shape: Untyped | None = ..., format: Untyped | None = ..., dtype: Untyped | None = ...) -> Untyped:
    ...

def diags(diagonals: Untyped, offsets: int = ..., shape: Untyped | None = ..., format: Untyped | None = ..., dtype: Untyped | None = ...) -> Untyped:
    ...

def identity(n: Untyped, dtype: str = ..., format: Untyped | None = ...) -> Untyped:
    ...

def eye_array(m: Untyped, n: Untyped | None = ..., *, k: int = ..., dtype: Untyped = ..., format: Untyped | None = ...) -> Untyped:
    ...

def eye(m: Untyped, n: Untyped | None = ..., k: int = ..., dtype: Untyped = ..., format: Untyped | None = ...) -> Untyped:
    ...

def kron(A: Untyped, B: Untyped, format: Untyped | None = ...) -> Untyped:
    ...

def kronsum(A: Untyped, B: Untyped, format: Untyped | None = ...) -> Untyped:
    ...

def hstack(blocks: Untyped, format: Untyped | None = ..., dtype: Untyped | None = ...) -> Untyped:
    ...

def vstack(blocks: Untyped, format: Untyped | None = ..., dtype: Untyped | None = ...) -> Untyped:
    ...

def bmat(blocks: Untyped, format: Untyped | None = ..., dtype: Untyped | None = ...) -> Untyped:
    ...

def block_array(blocks: Untyped, *, format: Untyped | None = ..., dtype: Untyped | None = ...) -> Untyped:
    ...

def block_diag(mats: Untyped, format: Untyped | None = ..., dtype: Untyped | None = ...) -> Untyped:
    ...

def random_array(shape: Untyped, *, density: float = ..., format: str = ..., dtype: Untyped | None = ..., random_state: Untyped | None = ..., data_sampler: Untyped | None = ...) -> Untyped:
    ...

def random(m: Untyped, n: Untyped, density: float = ..., format: str = ..., dtype: Untyped | None = ..., random_state: Untyped | None = ..., data_rvs: Untyped | None = ...) -> Untyped:
    ...

def rand(m: Untyped, n: Untyped, density: float = ..., format: str = ..., dtype: Untyped | None = ..., random_state: Untyped | None = ...) -> Untyped:
    ...

