"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__docformat__: str
def find(A) -> Untyped:
    ...

def tril(A, k: int = ..., format: Untyped | None = ...) -> Untyped:
    ...

def triu(A, k: int = ..., format: Untyped | None = ...) -> Untyped:
    ...

