"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

PICKLE_KWARGS: Untyped
def save_npz(file, matrix, compressed: bool = ...):
    ...

def load_npz(file) -> Untyped:
    ...

