"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

class _ScipyBackend:
    __ua_domain__: str
    @staticmethod
    def __ua_function__(method, args, kwargs) -> Untyped:
        ...
    


def set_global_backend(backend, coerce: bool = ..., only: bool = ..., try_last: bool = ...):
    ...

def register_backend(backend):
    ...

def set_backend(backend, coerce: bool = ..., only: bool = ...) -> Untyped:
    ...

def skip_backend(backend) -> Untyped:
    ...

