"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def fft(x, n: Untyped | None = ..., axis: int = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def ifft(x, n: Untyped | None = ..., axis: int = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def rfft(x, n: Untyped | None = ..., axis: int = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def irfft(x, n: Untyped | None = ..., axis: int = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def hfft(x, n: Untyped | None = ..., axis: int = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def ihfft(x, n: Untyped | None = ..., axis: int = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def fftn(x, s: Untyped | None = ..., axes: Untyped | None = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def ifftn(x, s: Untyped | None = ..., axes: Untyped | None = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def fft2(x, s: Untyped | None = ..., axes=..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def ifft2(x, s: Untyped | None = ..., axes=..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def rfftn(x, s: Untyped | None = ..., axes: Untyped | None = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def rfft2(x, s: Untyped | None = ..., axes=..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def irfftn(x, s: Untyped | None = ..., axes: Untyped | None = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def irfft2(x, s: Untyped | None = ..., axes=..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def hfftn(x, s: Untyped | None = ..., axes: Untyped | None = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def hfft2(x, s: Untyped | None = ..., axes=..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def ihfftn(x, s: Untyped | None = ..., axes: Untyped | None = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

def ihfft2(x, s: Untyped | None = ..., axes=..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, plan: Untyped | None = ...) -> Untyped:
    ...

