"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["fht", "fhtoffset", "ifht"]
def fht(a: Untyped, dln: Untyped, mu: Untyped, offset: float = ..., bias: float = ...) -> Untyped:
    ...

def ifht(A: Untyped, dln: Untyped, mu: Untyped, offset: float = ..., bias: float = ...) -> Untyped:
    ...

