"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def next_fast_len(target, real: bool = ...):
    ...

def prev_fast_len(target, real: bool = ...):
    ...

def fftfreq(n, d: float = ..., *, xp: Untyped | None = ..., device: Untyped | None = ...) -> Untyped:
    ...

def rfftfreq(n, d: float = ..., *, xp: Untyped | None = ..., device: Untyped | None = ...) -> Untyped:
    ...

def fftshift(x, axes: Untyped | None = ...) -> Untyped:
    ...

def ifftshift(x, axes: Untyped | None = ...) -> Untyped:
    ...

