"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def dctn(x, type: int = ..., s: Untyped | None = ..., axes: Untyped | None = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., *, orthogonalize: Untyped | None = ...) -> Untyped:
    ...

def idctn(x, type: int = ..., s: Untyped | None = ..., axes: Untyped | None = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., orthogonalize: Untyped | None = ...) -> Untyped:
    ...

def dstn(x, type: int = ..., s: Untyped | None = ..., axes: Untyped | None = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., orthogonalize: Untyped | None = ...) -> Untyped:
    ...

def idstn(x, type: int = ..., s: Untyped | None = ..., axes: Untyped | None = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., orthogonalize: Untyped | None = ...) -> Untyped:
    ...

def dct(x, type: int = ..., n: Untyped | None = ..., axis: int = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., orthogonalize: Untyped | None = ...) -> Untyped:
    ...

def idct(x, type: int = ..., n: Untyped | None = ..., axis: int = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., orthogonalize: Untyped | None = ...) -> Untyped:
    ...

def dst(x, type: int = ..., n: Untyped | None = ..., axis: int = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., orthogonalize: Untyped | None = ...) -> Untyped:
    ...

def idst(x, type: int = ..., n: Untyped | None = ..., axis: int = ..., norm: Untyped | None = ..., overwrite_x: bool = ..., workers: Untyped | None = ..., orthogonalize: Untyped | None = ...) -> Untyped:
    ...

