"""
This type stub file was generated by pyright.
"""

from typing import Final
from scipy._typing import Untyped, UntypedCallable
from .base import DenseOutput, OdeSolver

MAX_ORDER: Final = ...
NEWTON_MAXITER: Final = ...
MIN_FACTOR: Final = ...
MAX_FACTOR: Final = ...
def compute_R(order: Untyped, factor: Untyped) -> Untyped:
    ...

def change_D(D: Untyped, order: Untyped, factor: Untyped) -> Untyped:
    ...

def solve_bdf_system(fun: UntypedCallable, t_new: Untyped, y_predict: Untyped, c: Untyped, psi: Untyped, LU: Untyped, solve_lu: Untyped, scale: Untyped, tol: Untyped) -> Untyped:
    ...

class BDF(OdeSolver):
    max_step: Untyped
    h_abs: Untyped
    h_abs_old: Untyped
    error_norm_old: Untyped
    newton_tol: Untyped
    jac_factor: Untyped
    lu: Untyped
    solve_lu: Untyped
    I: Untyped
    gamma: Untyped
    alpha: Untyped
    error_const: Untyped
    D: Untyped
    order: int
    n_equal_steps: int
    LU: Untyped
    def __init__(self, /, fun: UntypedCallable, t0: Untyped, y0: Untyped, t_bound: Untyped, max_step: Untyped = ..., rtol: float = ..., atol: float = ..., jac: Untyped | None = ..., jac_sparsity: Untyped | None = ..., vectorized: bool = ..., first_step: Untyped | None = ..., **extraneous: Untyped) -> None:
        ...
    


class BdfDenseOutput(DenseOutput):
    order: Untyped
    t_shift: Untyped
    denom: Untyped
    D: Untyped
    def __init__(self, /, t_old: float, t: float, h: Untyped, order: Untyped, D: Untyped) -> None:
        ...
    


