"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped, UntypedCallable
from .base import DenseOutput, OdeSolver

class LSODA(OdeSolver):
    def __init__(self, /, fun: UntypedCallable, t0: Untyped, y0: Untyped, t_bound: Untyped, first_step: Untyped | None = ..., min_step: float = ..., max_step: Untyped = ..., rtol: float = ..., atol: float = ..., jac: Untyped | None = ..., lband: Untyped | None = ..., uband: Untyped | None = ..., vectorized: bool = ..., **extraneous: Untyped) -> None:
        ...
    


class LsodaDenseOutput(DenseOutput):
    h: Untyped
    yh: Untyped
    p: Untyped
    def __init__(self, /, t_old: float, t: float, h: Untyped, order: Untyped, yh: Untyped) -> None:
        ...
    


