"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["expm_multiply"]
def traceest(A, m3, seed: Untyped | None = ...) -> Untyped:
    ...

def expm_multiply(A, B, start: Untyped | None = ..., stop: Untyped | None = ..., num: Untyped | None = ..., endpoint: Untyped | None = ..., traceA: Untyped | None = ...) -> Untyped:
    ...

class LazyOperatorNormInfo:
    def __init__(self, A, A_1_norm: Untyped | None = ..., ell: int = ..., scale: int = ...) -> None:
        ...
    
    def set_scale(self, scale):
        ...
    
    def onenorm(self) -> Untyped:
        ...
    
    def d(self, p) -> Untyped:
        ...
    
    def alpha(self, p) -> Untyped:
        ...
    


