"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def delaunay_plot_2d(tri, ax: Untyped | None = ...) -> Untyped:
    ...

def convex_hull_plot_2d(hull, ax: Untyped | None = ...) -> Untyped:
    ...

def voronoi_plot_2d(vor, ax: Untyped | None = ..., **kw) -> Untyped:
    ...

