"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def calculate_solid_angles(R) -> Untyped:
    ...

class SphericalVoronoi:
    radius: Untyped
    points: Untyped
    center: Untyped
    def __init__(self, points, radius: int = ..., center: Untyped | None = ..., threshold: float = ...) -> None:
        ...
    
    def sort_vertices_of_regions(self):
        ...
    
    def calculate_areas(self) -> Untyped:
        ...
    


