"""
This type stub file was generated by pyright.
"""

from . import _ckdtree, _kdtree
from ._ckdtree import *
from ._kdtree import *

__all__: list[str] = ...
__all__ += _ckdtree.__all__
__all__ += _kdtree.__all__
