"""
This type stub file was generated by pyright.
"""

from typing_extensions import Never, deprecated

__all__: list[Never] = ...
@deprecated("will be removed in SciPy 2.0.0.")
def __dir__() -> list[Never]:
    ...

@deprecated("will be removed in SciPy 2.0.0.")
def __getattr__(name: str) -> Never:
    ...

