"""
This type stub file was generated by pyright.
"""

import io
from typing_extensions import override
from scipy._typing import Untyped

__all__ = ["mminfo", "mmread", "mmwrite"]
PARALLELISM: int
ALWAYS_FIND_SYMMETRY: bool
class _TextToBytesWrapper(io.BufferedReader):
    encoding: Untyped
    errors: Untyped
    def __init__(self, text_io_buffer, encoding: Untyped | None = ..., errors: Untyped | None = ..., **kwargs) -> None:
        ...
    
    @override
    def seek(self, offset: int, whence: int = ..., /) -> None:
        ...
    


def mmread(source) -> Untyped:
    ...

def mmwrite(target, a, comment: Untyped | None = ..., field: Untyped | None = ..., precision: Untyped | None = ..., symmetry: str = ...):
    ...

def mminfo(source) -> Untyped:
    ...

