"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["laplacian"]
def laplacian(csgraph: Untyped, normed: bool = ..., return_diag: bool = ..., use_out_degree: bool = ..., *, copy: bool = ..., form: str = ..., dtype: Untyped | None = ..., symmetrized: bool = ...) -> Untyped:
    ...

