"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def lobpcg(A, X, B: Untyped | None = ..., M: Untyped | None = ..., Y: Untyped | None = ..., tol: Untyped | None = ..., maxiter: Untyped | None = ..., largest: bool = ..., verbosityLevel: int = ..., retLambdaHistory: bool = ..., retResidualNormsHistory: bool = ..., restartControl: int = ...) -> Untyped:
    ...

