"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

izip = zip
def synchronized(func) -> Untyped:
    ...

def fmin_cobyla(func, x0, cons, args=..., consargs: Untyped | None = ..., rhobeg: float = ..., rhoend: float = ..., maxfun: int = ..., disp: Untyped | None = ..., catol: float = ..., *, callback: Untyped | None = ...) -> Untyped:
    ...

