"""
This type stub file was generated by pyright.
"""

import numpy.typing as npt
from collections.abc import Callable, Iterable
from typing import Any
from scipy._typing import Untyped
from ._constraints import Bounds
from ._optimize import OptimizeResult

__all__ = ["direct"]
ERROR_MESSAGES: tuple[str, ...]
SUCCESS_MESSAGES: tuple[str, ...]
def direct(func: Callable[[npt.ArrayLike, tuple[Any]], float], bounds: Iterable[float] | Bounds, *, args: tuple[Untyped, ...] = ..., eps: float = ..., maxfun: int | None = ..., maxiter: int = ..., locally_biased: bool = ..., f_min: float = ..., f_min_rtol: float = ..., vol_tol: float = ..., len_tol: float = ..., callback: Callable[[npt.ArrayLike], None] | None = ...) -> OptimizeResult:
    ...

