"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped
from scipy.sparse.linalg import LinearOperator as LinearOperator

def fmin_l_bfgs_b(func, x0, fprime: Untyped | None = ..., args=..., approx_grad: int = ..., bounds: Untyped | None = ..., m: int = ..., factr: float = ..., pgtol: float = ..., epsilon: float = ..., iprint: int = ..., maxfun: int = ..., maxiter: int = ..., disp: Untyped | None = ..., callback: Untyped | None = ..., maxls: int = ...) -> Untyped:
    ...

class LbfgsInvHessProduct(LinearOperator):
    sk: Untyped
    yk: Untyped
    n_corrs: Untyped
    rho: Untyped
    def __init__(self, sk, yk) -> None:
        ...
    
    def todense(self) -> Untyped:
        ...
    


