"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

class LineSearchWarning(RuntimeWarning):
    ...


def line_search_wolfe1(f, fprime, xk, pk, gfk: Untyped | None = ..., old_fval: Untyped | None = ..., old_old_fval: Untyped | None = ..., args=..., c1: float = ..., c2: float = ..., amax: int = ..., amin: float = ..., xtol: float = ...) -> Untyped:
    ...

def scalar_search_wolfe1(phi, derphi, phi0: Untyped | None = ..., old_phi0: Untyped | None = ..., derphi0: Untyped | None = ..., c1: float = ..., c2: float = ..., amax: int = ..., amin: float = ..., xtol: float = ...) -> Untyped:
    ...

line_search = ...
def line_search_wolfe2(f, myfprime, xk, pk, gfk: Untyped | None = ..., old_fval: Untyped | None = ..., old_old_fval: Untyped | None = ..., args=..., c1: float = ..., c2: float = ..., amax: Untyped | None = ..., extra_condition: Untyped | None = ..., maxiter: int = ...) -> Untyped:
    ...

def scalar_search_wolfe2(phi, derphi, phi0: Untyped | None = ..., old_phi0: Untyped | None = ..., derphi0: Untyped | None = ..., c1: float = ..., c2: float = ..., amax: Untyped | None = ..., extra_condition: Untyped | None = ..., maxiter: int = ...) -> Untyped:
    ...

def line_search_armijo(f, xk, pk, gfk, old_fval, args=..., c1: float = ..., alpha0: int = ...) -> Untyped:
    ...

def line_search_BFGS(f, xk, pk, gfk, old_fval, args=..., c1: float = ..., alpha0: int = ...) -> Untyped:
    ...

def scalar_search_armijo(phi, phi0, derphi0, c1: float = ..., alpha0: int = ..., amin: int = ...) -> Untyped:
    ...

