"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__docformat__: str
LINPROG_METHODS: Untyped
def linprog_verbose_callback(res) -> Untyped:
    ...

def linprog_terse_callback(res):
    ...

def linprog(c, A_ub: Untyped | None = ..., b_ub: Untyped | None = ..., A_eq: Untyped | None = ..., b_eq: Untyped | None = ..., bounds=..., method: str = ..., callback: Untyped | None = ..., options: Untyped | None = ..., x0: Untyped | None = ..., integrality: Untyped | None = ...) -> Untyped:
    ...

