"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["linear_sum_assignment"]
def linear_sum_assignment(*args: Untyped, **kwargs: Untyped) -> Untyped:
    ...

