"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def milp(c, *, integrality: Untyped | None = ..., bounds: Untyped | None = ..., constraints: Untyped | None = ..., options: Untyped | None = ...) -> Untyped:
    ...

