"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["minimize", "minimize_scalar"]
def minimize(fun, x0, args=..., method: Untyped | None = ..., jac: Untyped | None = ..., hess: Untyped | None = ..., hessp: Untyped | None = ..., bounds: Untyped | None = ..., constraints=..., tol: Untyped | None = ..., callback: Untyped | None = ..., options: Untyped | None = ...) -> Untyped:
    ...

def minimize_scalar(fun, bracket: Untyped | None = ..., bounds: Untyped | None = ..., args=..., method: Untyped | None = ..., tol: Untyped | None = ..., options: Untyped | None = ...) -> Untyped:
    ...

def standardize_bounds(bounds, x0, meth) -> Untyped:
    ...

def standardize_constraints(constraints, x0, meth) -> Untyped:
    ...

