"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

QUADRATIC_ASSIGNMENT_METHODS: Untyped
def quadratic_assignment(A, B, method: str = ..., options: Untyped | None = ...) -> Untyped:
    ...

