"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["root_scalar"]
ROOT_SCALAR_METHODS: Untyped
class MemoizeDer:
    fun: Untyped
    vals: Untyped
    x: Untyped
    n_calls: int
    def __init__(self, fun) -> None:
        ...
    
    def __call__(self, x, *args) -> Untyped:
        ...
    
    def fprime(self, x, *args) -> Untyped:
        ...
    
    def fprime2(self, x, *args) -> Untyped:
        ...
    
    def ncalls(self) -> Untyped:
        ...
    


def root_scalar(f, args=..., method: Untyped | None = ..., bracket: Untyped | None = ..., fprime: Untyped | None = ..., fprime2: Untyped | None = ..., x0: Untyped | None = ..., x1: Untyped | None = ..., xtol: Untyped | None = ..., rtol: Untyped | None = ..., maxiter: Untyped | None = ..., options: Untyped | None = ...) -> Untyped:
    ...

