"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped
from ._optimize import OptimizeResult

__all__ = ["root"]
def root(fun, x0, args=..., method: str = ..., jac: Untyped | None = ..., tol: Untyped | None = ..., callback: Untyped | None = ..., options: Untyped | None = ...) -> OptimizeResult:
    ...

