"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["approx_jacobian", "fmin_slsqp"]
def approx_jacobian(x: Untyped, func: Untyped, epsilon: Untyped, *args: Untyped) -> Untyped:
    ...

def fmin_slsqp(func: Untyped, x0: Untyped, eqcons: Untyped = ..., f_eqcons: Untyped | None = ..., ieqcons: Untyped = ..., f_ieqcons: Untyped | None = ..., bounds: Untyped = ..., fprime: Untyped | None = ..., fprime_eqcons: Untyped | None = ..., fprime_ieqcons: Untyped | None = ..., args: Untyped = ..., iter: int = ..., acc: float = ..., iprint: int = ..., disp: Untyped | None = ..., full_output: int = ..., epsilon: Untyped = ..., callback: Untyped | None = ...) -> Untyped:
    ...

