"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["fmin_tnc"]
MSG_NONE: int
MSG_ITER: int
MSG_INFO: int
MSG_VERS: int
MSG_EXIT: int
MSG_ALL: Untyped
MSGS: Untyped
INFEASIBLE: int
LOCALMINIMUM: int
FCONVERGED: int
XCONVERGED: int
MAXFUN: int
LSFAIL: int
CONSTANT: int
NOPROGRESS: int
USERABORT: int
RCSTRINGS: Untyped
def fmin_tnc(func, x0, fprime: Untyped | None = ..., args=..., approx_grad: int = ..., bounds: Untyped | None = ..., epsilon: float = ..., scale: Untyped | None = ..., offset: Untyped | None = ..., messages=..., maxCGit: int = ..., maxfun: Untyped | None = ..., eta: int = ..., stepmx: int = ..., accuracy: int = ..., fmin: int = ..., ftol: int = ..., xtol: int = ..., pgtol: int = ..., rescale: int = ..., disp: Untyped | None = ..., callback: Untyped | None = ...) -> Untyped:
    ...

