"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

__all__ = ["svds"]
def svds(A, k: int = ..., ncv: Untyped | None = ..., tol: int = ..., which: str = ..., v0: Untyped | None = ..., maxiter: Untyped | None = ..., return_singular_vectors: bool = ..., solver: str = ..., random_state: Untyped | None = ..., options: Untyped | None = ...) -> Untyped:
    ...

