"""
This type stub file was generated by pyright.
"""

from typing import Literal, TypeAlias
from ._common import ConfidenceInterval

__all__ = ["BinomTestResult", "binomtest"]
_Alternative: TypeAlias = Literal["two-sided", "less", "greater"]
class BinomTestResult:
    k: int
    n: int
    alternative: _Alternative
    statistic: float
    pvalue: float
    def __init__(self, k: int, n: int, alternative: _Alternative, statistic: float, pvalue: float) -> None:
        ...
    
    def proportion_ci(self, confidence_level: float = ..., method: Literal["exact", "wilson", "wilsoncc"] = ...) -> ConfidenceInterval:
        ...
    


def binomtest(k: int, n: int, p: float = ..., alternative: _Alternative = ...) -> BinomTestResult:
    ...

