"""
This type stub file was generated by pyright.
"""

import numpy.typing as npt
from typing import Literal
from ._resampling import PermutationMethod, PermutationTestResult

__all__ = ["bws_test"]
def bws_test(x: npt.ArrayLike, y: npt.ArrayLike, *, alternative: Literal["two-sided", "less", "greater"] = ..., method: PermutationMethod | None = ...) -> PermutationTestResult:
    ...

