"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

CrosstabResult: Untyped
def crosstab(*args, levels: Untyped | None = ..., sparse: bool = ...) -> Untyped:
    ...

