"""
This type stub file was generated by pyright.
"""

import numpy as np
import numpy.typing as npt
import scipy._typing as spt
from typing import Any, Literal

__all__ = ["differential_entropy", "entropy"]
def entropy(pk: npt.ArrayLike, qk: npt.ArrayLike | None = ..., base: float | None = ..., axis: int = ..., *, nan_policy: spt.NanPolicy = ..., keepdims: bool = ...) -> np.floating[Any] | npt.NDArray[np.floating[Any]]:
    ...

def differential_entropy(values: npt.ArrayLike, *, window_length: int | None = ..., base: float | None = ..., axis: int = ..., method: Literal["vasicek", "van es", "ebrahimi", "correa", "auto"] = ..., nan_policy: spt.NanPolicy = ..., keepdims: bool = ...) -> np.floating[Any] | npt.NDArray[np.floating[Any]]:
    ...

