"""
This type stub file was generated by pyright.
"""

from typing import NamedTuple
from scipy._typing import Untyped

class FitResult:
    discrete: Untyped
    pxf: Untyped
    params: Untyped
    success: Untyped
    message: Untyped
    def __init__(self, dist, data, discrete, res) -> None:
        ...
    
    def nllf(self, params: Untyped | None = ..., data: Untyped | None = ...) -> Untyped:
        ...
    
    def plot(self, ax: Untyped | None = ..., *, plot_type: str = ...) -> Untyped:
        ...
    


def fit(dist, data, bounds: Untyped | None = ..., *, guess: Untyped | None = ..., method: str = ..., optimizer=...) -> Untyped:
    ...

class GoodnessOfFitResult(NamedTuple):
    fit_result: Untyped
    statistic: Untyped
    pvalue: Untyped
    null_distribution: Untyped
    ...


def goodness_of_fit(dist, data, *, known_params: Untyped | None = ..., fit_params: Untyped | None = ..., guessed_params: Untyped | None = ..., statistic: str = ..., n_mc_samples: int = ..., random_state: Untyped | None = ...) -> Untyped:
    ...

