"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import NamedTuple
from scipy._typing import Untyped, UntypedArray

__all__ = ["barnard_exact", "boschloo_exact", "cramervonmises", "cramervonmises_2samp", "epps_singleton_2samp", "poisson_means_test", "somersd", "tukey_hsd"]
class Epps_Singleton_2sampResult(NamedTuple):
    statistic: Untyped
    pvalue: Untyped
    ...


@dataclass
class SomersDResult:
    statistic: float
    pvalue: float
    table: UntypedArray
    ...


@dataclass
class BarnardExactResult:
    statistic: float
    pvalue: float
    ...


@dataclass
class BoschlooExactResult:
    statistic: float
    pvalue: float
    ...


class TukeyHSDResult:
    statistic: Untyped
    pvalue: Untyped
    def __init__(self, statistic, pvalue, _nobs, _ntreatments, _stand_err) -> None:
        ...
    
    def confidence_interval(self, confidence_level: float = ...) -> Untyped:
        ...
    


class CramerVonMisesResult:
    statistic: Untyped
    pvalue: Untyped
    def __init__(self, statistic, pvalue) -> None:
        ...
    


def epps_singleton_2samp(x, y, t=...) -> Untyped:
    ...

def poisson_means_test(k1, n1, k2, n2, *, diff: int = ..., alternative: str = ...) -> Untyped:
    ...

def cramervonmises(rvs, cdf, args=...) -> Untyped:
    ...

def somersd(x, y: Untyped | None = ..., alternative: str = ...) -> Untyped:
    ...

def barnard_exact(table, alternative: str = ..., pooled: bool = ..., n: int = ...) -> Untyped:
    ...

def boschloo_exact(table, alternative: str = ..., n: int = ...) -> Untyped:
    ...

def cramervonmises_2samp(x, y, method: str = ...) -> Untyped:
    ...

def tukey_hsd(*args) -> Untyped:
    ...

