"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def hdquantiles(data, prob=..., axis: Untyped | None = ..., var: bool = ...) -> Untyped:
    ...

def hdmedian(data, axis: int = ..., var: bool = ...) -> Untyped:
    ...

def hdquantiles_sd(data, prob=..., axis: Untyped | None = ...) -> Untyped:
    ...

def trimmed_mean_ci(data, limits=..., inclusive=..., alpha: float = ..., axis: Untyped | None = ...) -> Untyped:
    ...

def mjci(data, prob=..., axis: Untyped | None = ...) -> Untyped:
    ...

def mquantiles_cimj(data, prob=..., alpha: float = ..., axis: Untyped | None = ...) -> Untyped:
    ...

def median_cihs(data, alpha: float = ..., axis: Untyped | None = ...) -> Untyped:
    ...

def compare_medians_ms(group_1, group_2, axis: Untyped | None = ...) -> Untyped:
    ...

def idealfourths(data, axis: Untyped | None = ...) -> Untyped:
    ...

def rsh(data, points: Untyped | None = ...) -> Untyped:
    ...

