"""
This type stub file was generated by pyright.
"""

import numpy as np
import numpy.typing as npt
from dataclasses import dataclass
from typing import Literal
from scipy._lib._util import DecimalNumber as DecimalNumber, SeedType as SeedType
from scipy.stats._common import ConfidenceInterval as ConfidenceInterval

__all__ = ["dunnett"]
@dataclass
class DunnettResult:
    statistic: npt.NDArray[np.float64]
    pvalue: npt.NDArray[np.float64]
    def confidence_interval(self, confidence_level: DecimalNumber = ...) -> ConfidenceInterval:
        ...
    


def dunnett(*samples: npt.ArrayLike, control: npt.ArrayLike, alternative: Literal["two-sided", "less", "greater"] = ..., random_state: SeedType = ...) -> DunnettResult:
    ...

