"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

class OddsRatioResult:
    statistic: Untyped
    def __init__(self, _table, _kind, statistic) -> None:
        ...
    
    def confidence_interval(self, confidence_level: float = ..., alternative: str = ...) -> Untyped:
        ...
    


def odds_ratio(table, *, kind: str = ...) -> Untyped:
    ...

