"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from scipy._typing import Untyped

@dataclass
class RelativeRiskResult:
    relative_risk: float
    exposed_cases: int
    exposed_total: int
    control_cases: int
    control_total: int
    def confidence_interval(self, confidence_level: float = ...) -> Untyped:
        ...
    


def relative_risk(exposed_cases, exposed_total, control_cases, control_total) -> Untyped:
    ...

