"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from scipy._typing import Untyped, UntypedArray
from ._common import ConfidenceInterval

__all__ = ["bootstrap", "monte_carlo_test", "permutation_test"]
@dataclass
class BootstrapResult:
    confidence_interval: ConfidenceInterval
    bootstrap_distribution: UntypedArray
    standard_error: float | UntypedArray
    ...


@dataclass
class MonteCarloTestResult:
    statistic: float | UntypedArray
    pvalue: float | UntypedArray
    null_distribution: UntypedArray
    ...


@dataclass
class PowerResult:
    power: float | UntypedArray
    pvalues: float | UntypedArray
    ...


@dataclass
class PermutationTestResult:
    statistic: float | UntypedArray
    pvalue: float | UntypedArray
    null_distribution: UntypedArray
    ...


@dataclass
class ResamplingMethod:
    n_resamples: int = ...
    batch: int = ...


@dataclass
class MonteCarloMethod(ResamplingMethod):
    rvs: Untyped = ...


@dataclass
class PermutationMethod(ResamplingMethod):
    random_state: Untyped = ...


@dataclass
class BootstrapMethod(ResamplingMethod):
    random_state: Untyped = ...
    method: str = ...


def bootstrap(data, statistic, *, n_resamples: int = ..., batch: Untyped | None = ..., vectorized: Untyped | None = ..., paired: bool = ..., axis: int = ..., confidence_level: float = ..., alternative: str = ..., method: str = ..., bootstrap_result: Untyped | None = ..., random_state: Untyped | None = ...) -> Untyped:
    ...

def monte_carlo_test(data, rvs, statistic, *, vectorized: Untyped | None = ..., n_resamples: int = ..., batch: Untyped | None = ..., alternative: str = ..., axis: int = ...) -> Untyped:
    ...

def power(test, rvs, n_observations, *, significance: float = ..., vectorized: Untyped | None = ..., n_resamples: int = ..., batch: Untyped | None = ..., kwargs: Untyped | None = ...) -> Untyped:
    ...

def permutation_test(data, statistic, *, permutation_type: str = ..., vectorized: Untyped | None = ..., n_resamples: int = ..., batch: Untyped | None = ..., alternative: str = ..., axis: int = ..., random_state: Untyped | None = ...) -> Untyped:
    ...

