"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

TheilslopesResult: Untyped
SiegelslopesResult: Untyped
def theilslopes(y, x: Untyped | None = ..., alpha: float = ..., method: str = ...) -> Untyped:
    ...

def siegelslopes(y, x: Untyped | None = ..., method: str = ...) -> Untyped:
    ...

