"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def variation(a, axis: int = ..., nan_policy: str = ..., ddof: int = ..., *, keepdims: bool = ...) -> Untyped:
    ...

