"""
This type stub file was generated by pyright.
"""

class DegenerateDataWarning(RuntimeWarning):
    args: tuple[str | None]
    def __init__(self, msg: str | None = ...) -> None:
        ...
    


class ConstantInputWarning(DegenerateDataWarning):
    ...


class NearConstantInputWarning(DegenerateDataWarning):
    ...


class FitError(RuntimeError):
    ...


