"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def margins(a) -> Untyped:
    ...

def expected_freq(observed) -> Untyped:
    ...

Chi2ContingencyResult: Untyped
def chi2_contingency(observed, correction: bool = ..., lambda_: Untyped | None = ...) -> Untyped:
    ...

def association(observed, method: str = ..., correction: bool = ..., lambda_: Untyped | None = ...) -> Untyped:
    ...

