"""
This type stub file was generated by pyright.
"""

from . import _continuous_distns, _discrete_distns
from ._continuous_distns import *
from ._discrete_distns import *

__all__ = ["entropy", "levy_stable", "rv_continuous", "rv_discrete", "rv_frozen"]
__all__ += _continuous_distns.__all__
__all__ += _discrete_distns.__all__
