"""
This type stub file was generated by pyright.
"""

import numpy as np
import numpy.typing as npt
from typing import TypeAlias

__all__ = ["bandwidth", "ishermitian", "issymmetric"]
_Numeric: TypeAlias = (np.int8 | np.int16 | np.int32 | np.int64 | np.uint8 | np.uint16 | np.uint32 | np.uint64 | np.float32 | np.float64 | np.longdouble | np.complex64 | np.complex128)
def bandwidth(a: npt.NDArray[_Numeric]) -> tuple[int, int]:
    ...

def issymmetric(a: npt.NDArray[_Numeric], atol: float | None = ..., rtol: float | None = ...) -> bool:
    ...

def ishermitian(a: npt.NDArray[_Numeric], atol: float | None = ..., rtol: float | None = ...) -> bool:
    ...

