"""
This type stub file was generated by pyright.
"""

import numpy as np
import numpy.typing as npt
from typing import TypeAlias

__all__ = ["ldl"]
_Array_i_1d: TypeAlias = np.ndarray[tuple[int], np.dtype[np.intp]]
_Array_fc_2d: TypeAlias = np.ndarray[tuple[int, int], np.dtype[np.inexact[npt.NBitBase]]]
def ldl(A: npt.ArrayLike, lower: bool = ..., hermitian: bool = ..., overwrite_a: bool = ..., check_finite: bool = ...) -> tuple[_Array_fc_2d, _Array_fc_2d, _Array_i_1d]:
    ...

