"""
This type stub file was generated by pyright.
"""

import numpy as np
import numpy.typing as npt
from typing import Literal, TypeAlias

__all__ = ["qr_delete", "qr_insert", "qr_update"]
_Which: TypeAlias = Literal["row", "col"]
def qr_delete(Q: npt.ArrayLike, R: npt.ArrayLike, k: int, p: int = ..., which: _Which = ..., overwrite_qr: bool = ..., check_finite: bool = ...) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]:
    ...

def qr_insert(Q: npt.ArrayLike, R: npt.ArrayLike, u: npt.ArrayLike, k: int, which: _Which = ..., rcond: float | None = ..., overwrite_qru: bool = ..., check_finite: bool = ...) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]:
    ...

def qr_update(Q: npt.ArrayLike, R: npt.ArrayLike, u: npt.ArrayLike, v: npt.ArrayLike, overwrite_qruv: bool = ..., check_finite: bool = ...) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]:
    ...

