"""
This type stub file was generated by pyright.
"""

import numpy as np
import numpy.typing as npt
from typing import Literal, TypeAlias, overload

__all__ = ["sqrtm"]
_Array_fc_2d: TypeAlias = np.ndarray[tuple[int, int], np.dtype[np.inexact[npt.NBitBase]]]
class SqrtmError(np.linalg.LinAlgError):
    ...


@overload
def sqrtm(A: npt.ArrayLike, disp: Literal[True] = ..., blocksize: int = ...) -> _Array_fc_2d:
    ...

@overload
def sqrtm(A: npt.ArrayLike, disp: Literal[False], blocksize: int = ...) -> tuple[_Array_fc_2d, float | np.float64]:
    ...

