"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped
from scipy.optimize import OptimizeResult

TERMINATION_MESSAGES: Untyped
FROM_MINPACK_TO_COMMON: Untyped
IMPLEMENTED_LOSSES: Untyped
def call_minpack(fun, x0, jac, ftol, xtol, gtol, max_nfev, x_scale, diff_step) -> Untyped:
    ...

def prepare_bounds(bounds, n) -> Untyped:
    ...

def check_tolerance(ftol, xtol, gtol, method) -> Untyped:
    ...

def check_x_scale(x_scale, x0) -> Untyped:
    ...

def check_jac_sparsity(jac_sparsity, m, n) -> Untyped:
    ...

def huber(z, rho, cost_only):
    ...

def soft_l1(z, rho, cost_only):
    ...

def cauchy(z, rho, cost_only):
    ...

def arctan(z, rho, cost_only):
    ...

def construct_loss_function(m, loss, f_scale) -> Untyped:
    ...

def least_squares(fun, x0, jac: str = ..., bounds=..., method: str = ..., ftol: float = ..., xtol: float = ..., gtol: float = ..., x_scale: float = ..., loss: str = ..., f_scale: float = ..., diff_step: Untyped | None = ..., tr_solver: Untyped | None = ..., tr_options: Untyped | None = ..., jac_sparsity: Untyped | None = ..., max_nfev: Untyped | None = ..., verbose: int = ..., args=..., kwargs: Untyped | None = ...) -> OptimizeResult:
    ...

