"""
This type stub file was generated by pyright.
"""

from typing import Final
from scipy._typing import Untyped
from scipy.optimize import OptimizeResult

TERMINATION_MESSAGES: Final[dict[int, str]]
def prepare_bounds(bounds, n) -> Untyped:
    ...

def lsq_linear(A, b, bounds=..., method: str = ..., tol: float = ..., lsq_solver: Untyped | None = ..., lsmr_tol: Untyped | None = ..., max_iter: Untyped | None = ..., verbose: int = ..., *, lsmr_maxiter: Untyped | None = ...) -> OptimizeResult:
    ...

