"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def fourier_gaussian(input, sigma, n: int = ..., axis: int = ..., output: Untyped | None = ...) -> Untyped:
    ...

def fourier_uniform(input, size, n: int = ..., axis: int = ..., output: Untyped | None = ...) -> Untyped:
    ...

def fourier_ellipsoid(input, size, n: int = ..., axis: int = ..., output: Untyped | None = ...) -> Untyped:
    ...

def fourier_shift(input, shift, n: int = ..., axis: int = ..., output: Untyped | None = ...) -> Untyped:
    ...

