"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def spline_filter1d(input, order: int = ..., axis: int = ..., output=..., mode: str = ...) -> Untyped:
    ...

def spline_filter(input, order: int = ..., output=..., mode: str = ...) -> Untyped:
    ...

def geometric_transform(input, mapping, output_shape: Untyped | None = ..., output: Untyped | None = ..., order: int = ..., mode: str = ..., cval: float = ..., prefilter: bool = ..., extra_arguments=..., extra_keywords: Untyped | None = ...) -> Untyped:
    ...

def map_coordinates(input, coordinates, output: Untyped | None = ..., order: int = ..., mode: str = ..., cval: float = ..., prefilter: bool = ...) -> Untyped:
    ...

def affine_transform(input, matrix, offset: float = ..., output_shape: Untyped | None = ..., output: Untyped | None = ..., order: int = ..., mode: str = ..., cval: float = ..., prefilter: bool = ...) -> Untyped:
    ...

def shift(input, shift, output: Untyped | None = ..., order: int = ..., mode: str = ..., cval: float = ..., prefilter: bool = ...) -> Untyped:
    ...

def zoom(input, zoom, output: Untyped | None = ..., order: int = ..., mode: str = ..., cval: float = ..., prefilter: bool = ..., *, grid_mode: bool = ...) -> Untyped:
    ...

def rotate(input, angle, axes=..., reshape: bool = ..., output: Untyped | None = ..., order: int = ..., mode: str = ..., cval: float = ..., prefilter: bool = ...) -> Untyped:
    ...

