"""
This type stub file was generated by pyright.
"""

from scipy._typing import Untyped

def label(input, structure: Untyped | None = ..., output: Untyped | None = ...) -> Untyped:
    ...

def find_objects(input, max_label: int = ...) -> Untyped:
    ...

def value_indices(arr, *, ignore_value: Untyped | None = ...) -> Untyped:
    ...

def labeled_comprehension(input, labels, index, func, out_dtype, default, pass_positions: bool = ...) -> Untyped:
    ...

def sum(input, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def sum_labels(input, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def mean(input, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def variance(input, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def standard_deviation(input, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def minimum(input, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def maximum(input, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def median(input, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def minimum_position(input, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def maximum_position(input, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def extrema(input, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def center_of_mass(input, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def histogram(input, min, max, bins, labels: Untyped | None = ..., index: Untyped | None = ...) -> Untyped:
    ...

def watershed_ift(input, markers, structure: Untyped | None = ..., output: Untyped | None = ...) -> Untyped:
    ...

